### ISSUE TITLE
Multiple package.json cannot be updated

### ISSUE THREAD

**Issue by domus71** [willasm/version-inc#3]
Hi there,

I have various projects with multiple package.json files (server API / client front-end).

Is there a way to activate version-inc ?

Thanks,
Costis

**Comment by willasm** [comment]
So sorry that I didn't see this sooner. I have been without a computer for quite a while but that has finally changed. You may have figured this out already but you can add as many files to be updated as you want. Use the command `Version Inc: Edit Settings for Update Files` from the command palette and edit the file as needed. Detailed instructions are included in the [README.md](https://github.com/willasm/version-inc/blob/develop/README.md) file. If you need further explanation of the process just let me know.

**Comment by domus71** [comment]
The extension does not load! I have two folders (client - React project & server - Nodejs project). I use the extension without issues in one folder projects. I even add the different folders ${workspaceFolder}\\client & ${workspaceFolder}\\server, but the extension does not apper.

**Comment by willasm** [comment]
That is strange. Are you sure you have a package.json file in the root of your project? It will not load if it does not find one. Are you able to open the example files with the command `Version Inc: Edit Example Files` from the command palette? Just testing it now and I am having a problem getting the example files to update. I think vscode must of changed something regarding the global storage as I cannot get the example files to update even if I supply the full path in the settings file to the example files in global storage? It is working for me with files in the in the projects root folder and any folders below that though.

It must be late, lol. I just realized that the example files had the "Enable": true" setting set to false. They are updating correctly now. Check that setting in the settings file and let me know if it is set correctly.

**Comment by willasm** [comment]
Just thought more about what you said. Do you have a package.json in each of the folders, client and server? If that is the case you would still need one in the root folder as that is where it is searched for. If so you could just create a dummy package.json file in the root folder. All it would need to contain is the line `"version": "1.0.0"` that would give the extension something to update in the root. Then just add the other files to the settings file.

**Comment by domus71** [comment]
There is not a package.json in root folder. I created one and the extension appreared. I have two package.josn, one in client and one in server folder and these I need to update regularly.

**Comment by willasm** [comment]
You can add both to the settings file like this... (Add any other files you want to update as well)

```json
[
	{
		"Filename": "package.json",
		"FileLocation": "client",
		"Enable": true,
		"RetainLine": true,
		"InsertBefore": "",
		"InsertAfter": "",
		"TrimTextStart": 0,
		"TrimTextEnd": 0
	},
	{
		"Filename": "package.json",
		"FileLocation": "server",
		"Enable": true,
		"RetainLine": true,
		"InsertBefore": "",
		"InsertAfter": "",
		"TrimTextStart": 0,
		"TrimTextEnd": 0
	}
]
```

You can also write `"Filename": "client\\package.json"` and `"FileLocation": ""` if you prefer.

**Comment by domus71** [comment]
I have already done this! But it seems not to increase the version value... If I put V-INV in my package.json files, but it works only the first time.

**Comment by willasm** [comment]
Yes this is a problem that needs to be fixed. If json supported comments this could be done easily by setting the `"RetainLine": "true"` and commenting the `"version": "1.0.0"` line but that won't work in a json file as it will create a duplicate line which will cause an error. I will have to add support for multiple package.json files in order to get this to work. I will look at it tomorrow as it is 4:30am here now and I need to get some sleep.

**Comment by willasm** [comment]
Just wanted to let you know that I am still working on this. It turned out to be much more involved than I thought it would be. Each package.json file has its own version independent of the others so that had to be taken into consideration. I have added a new setting allowing the user to define additional locations for for other package.json files, as many as you need. The default is set to client and server as that is very common. I currently have the updating for all package.json files in their defined locations working. If updating all, you will be prompted for increment type (patch, minor, major) for each defined package. The code still needs a bit of fine tuning and bug testing. I'll also have to do the same for decrementing the versions, although that is just basically just copying the changes from the incrementing code with some small changes, so that won't take as long.

Do note that the package.json in the workspace root is still a requirement. I'm not sure why you didn't have one in the root folder? I have never seen that in any project, for example most of vscode's language extensions use a client and server and all of them have package.json files in the root as well as the client and server folders. At any rate, I suggest you run npm init in the root folder to generate a basic package.json and set the version to what you want for the entire project. Then the client and server can have there own versions which makes sense as your usually only updating one at a time.

Anyhow, hopefully I will have this done soon, it is very close to being done now.

**Comment by willasm** [comment]
This has been completed and is working correctly. I just need to update the documentation before uploading the update. Should be available for download by tomorrow morning at the latest.

**Comment by willasm** [comment]
Uploaded as version 1.1.0 and is available to update within vscode. Let me know if this is working for you.

**Comment by domus71** [comment]
Great! It seems to work fine. Although, you need to have a dummy package.json on root folder to load the extension.

Many thanks

**Comment by domus71** [comment]
When you have more than one package.json files, it will be nice to have a "Maintain version number" option in menu (Patch/Minor/Major).

**Comment by willasm** [comment]
By "Maintain version number" do you mean you want one to not update? If so just you can also just hit 'Esc' to skip updating the currently selected file. You can also stop getting prompted for that particular file by removing its folder in the settings. Go to settings (ctrl+,) -> Extensions (on the left) and scroll down to 'Version INC' and delete from the list 'Package JSON Paths' the folder containing the package.json file you want to stop updating. You may want to do this using the 'Workspace' tab at the top left, as this will then only apply to that project. If you remove it from the 'User' settings tab, it will be removed from all projects.

**Comment by willasm** [comment]
By the way you actually should have a package.json in the root just to maintain the overall version of your project. The ones in client and server should have their own version numbers that are only updated when making changes to that component. They are the ones that will contain all your dependencies as well. The one in the root folder should basically contain just the projects name, description, and overall version number, no need to declare dependencies in that one. This is the most common way of doing this in this situation.

**Comment by willasm** [comment]
I should try to explain my reasoning for requiring a package file in the root folder. The main purpose of this extension is to update the version number in the package file and if it can't find it there is no reason for it to even load. The VS code activation event I use to load the extension "workspaceContains:package.json" actually expects a package.json file to be in the root, where everyone should have one, and if it is not there my extension just won't activate. The only way around that would be to manually search every sub-folder looking for package files but that would only be possible if I let the extension load first, then run the search code, and if no package is found then I would have to force my extension to unload. That is definitely not the right way to load an extension. The Marketplace would probably flag my extension as well for the unusual code as an extension, once loaded should only ever be disabled by the end user and never by the extension itself.

That was rather long but I hope it clears that up for you.
